version: '2'

services:
  couchbase:
    image: mertaksoyy/couchbase-custom:latest
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=admin123
      - COUCHBASE_BUCKET=ToDoApp
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  backend:
    image: mertaksoyy/todoapp:latest
    ports:
      - "9100:9100"
    environment:
      - COUCHBASE_HOST=couchbase://127.0.0.1
      - COUCHBASE_BUCKET=ToDoApp
    restart: always
    depends_on:
      - couchbase
    networks:
      - vpcbr

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1